global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@tender-system.com'
  smtp_auth_username: 'alerts@tender-system.com'
  smtp_auth_password: 'your_email_password'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@tender-system.com'
        subject: '[CRITICAL] 招标系统告警'
        body: |
          告警名称: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          告警详情: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          告警时间: {{ range .Alerts }}{{ .StartsAt }}{{ end }}
          告警级别: 严重
    webhook_configs:
      - url: 'http://localhost:5001/webhook/critical'
        send_resolved: true

  - name: 'warning-alerts'
    email_configs:
      - to: 'ops@tender-system.com'
        subject: '[WARNING] 招标系统告警'
        body: |
          告警名称: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          告警详情: {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          告警时间: {{ range .Alerts }}{{ .StartsAt }}{{ end }}
          告警级别: 警告

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']