"""r m some fields

Revision ID: 0873f42f9cb5
Revises: 6731953f4a4a
Create Date: 2025-06-04 14:11:44.382686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0873f42f9cb5'
down_revision: Union[str, None] = '6731953f4a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_contents', 'page')
    op.drop_column('parsed_contents', 'content_type')
    op.drop_column('settings', 'ocr_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('ocr_enabled', sa.BOOLEAN(), nullable=True))
    op.add_column('parsed_contents', sa.Column('content_type', sa.VARCHAR(length=32), nullable=True))
    op.add_column('parsed_contents', sa.Column('page', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
