"""add_tender_project_model

Revision ID: 3392a7aa31b1
Revises: fe2ea4b329bb
Create Date: 2025-07-30 11:54:00.823691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3392a7aa31b1'
down_revision: Union[str, None] = 'fe2ea4b329bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ANALYZING', 'ANALYZED', 'OUTLINING', 'OUTLINED', 'GENERATING', 'GENERATED', 'EXPORTING', 'COMPLETED', 'FAILED', name='tenderstatus'), nullable=True),
    sa.Column('minio_path', sa.String(length=512), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_projects_tenant_id'), 'tender_projects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tender_projects_user_id'), 'tender_projects', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_projects_user_id'), table_name='tender_projects')
    op.drop_index(op.f('ix_tender_projects_tenant_id'), table_name='tender_projects')
    op.drop_table('tender_projects')
    # ### end Alembic commands ###
