"""add_bid_generator_models

Revision ID: 9c1ab1804be8
Revises: fe2ea4b329bb
Create Date: 2025-08-01 15:35:17.409945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1ab1804be8'
down_revision: Union[str, None] = 'fe2ea4b329bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'PARSING', 'ANALYZING', 'OUTLINE_GENERATED', 'DOCUMENT_GENERATING', 'COMPLETED', 'FAILED', name='projectstatus'), nullable=True),
    sa.Column('original_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['original_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('bid_outlines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['bid_outlines.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_outlines_user_id'), 'bid_outlines', ['user_id'], unique=False)
    op.create_table('requirement_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('project_overview', sa.Text(), nullable=True),
    sa.Column('client_info', sa.Text(), nullable=True),
    sa.Column('budget_info', sa.Text(), nullable=True),
    sa.Column('detailed_requirements', sa.Text(), nullable=True),
    sa.Column('critical_requirements', sa.Text(), nullable=True),
    sa.Column('important_requirements', sa.Text(), nullable=True),
    sa.Column('general_requirements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_analysis_user_id'), 'requirement_analysis', ['user_id'], unique=False)
    op.create_table('bid_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('outline_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'EDITED', 'FINALIZED', name='documentstatus'), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outline_id'], ['bid_outlines.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bid_documents_user_id'), 'bid_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bid_documents_user_id'), table_name='bid_documents')
    op.drop_table('bid_documents')
    op.drop_index(op.f('ix_requirement_analysis_user_id'), table_name='requirement_analysis')
    op.drop_table('requirement_analysis')
    op.drop_index(op.f('ix_bid_outlines_user_id'), table_name='bid_outlines')
    op.drop_table('bid_outlines')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
